app = "loglify-service"  # <-- change this to something unique (e.g. springboot-jwt-app)

primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
