

spring:
  data:
    mongodb:
      uri: mongodb+srv://ankitatfreelancing:yCIOd5cpk78gZmu1@cluster0.xo8zkuu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: systemdb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ankitsingh300303@gmail.com
    password: nybgpybokzkjbewc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  redis:
    uri: redis://default:LJ0KTVt1x11amQgatekclizaFfbJLJGI@redis-12059.crce206.ap-south-1-1.ec2.redns.redis-cloud.com:12059


server:
  port: 8081
  servlet:
    context-path: /journal



weather:
  api:
    key: 6c39c3644815cd20bacd61c9bd270889


